CREATE TABLE [SGT].[PseudoST] (
    [Postcode 1]                      VARCHAR (500) NULL,
    [Postcode 2]                      VARCHAR (500) NULL,
    [Postcode 3]                      VARCHAR (500) NULL,
    [Date Introduced]                 VARCHAR (500) NULL,
    [User Type]                       VARCHAR (500) NULL,
    [Easting]                         VARCHAR (500) NULL,
    [Northing]                        VARCHAR (500) NULL,
    [Positional Quality]              VARCHAR (500) NULL,
    [County Code]                     VARCHAR (500) NULL,
    [County Name]                     VARCHAR (500) NULL,
    [Local Authority Code]            VARCHAR (500) NULL,
    [Local Authority Name]            VARCHAR (500) NULL,
    [Ward Code]                       VARCHAR (500) NULL,
    [Ward Name]                       VARCHAR (500) NULL,
    [Country Code]                    VARCHAR (500) NULL,
    [Country Name]                    VARCHAR (500) NULL,
    [Region Code]                     VARCHAR (500) NULL,
    [Region Name]                     VARCHAR (500) NULL,
    [Parliamentary Constituency Code] VARCHAR (500) NULL,
    [Parliamentary Constituency Name] VARCHAR (500) NULL,
    [European Electoral Region Code]  VARCHAR (500) NULL,
    [European Electoral Region Name]  VARCHAR (500) NULL,
    [Primary Care Trust Code]         VARCHAR (500) NULL,
    [Primary Care Trust Name]         VARCHAR (500) NULL,
    [Lower Super Output Area Code]    VARCHAR (500) NULL,
    [Lower Super Output Area Name]    VARCHAR (500) NULL,
    [Middle Super Output Area Code]   VARCHAR (500) NULL,
    [Middle Super Output Area Name]   VARCHAR (500) NULL,
    [Output Area Classification Code] VARCHAR (500) NULL,
    [Output Area Classification Name] VARCHAR (500) NULL,
    [Longitude]                       VARCHAR (500) NULL,
    [Latitude]                        VARCHAR (500) NULL,
    [Spatial Accuracy]                VARCHAR (500) NULL,
    [Last Uploaded]                   VARCHAR (500) NULL,
    [Location]                        VARCHAR (500) NULL,
    [Socrata ID]                      VARCHAR (500) NULL
);

