CREATE TABLE [SGT].[ST] (
    [Postcode 1]                      NVARCHAR (255) NULL,
    [Postcode 2]                      NVARCHAR (255) NULL,
    [Postcode 3]                      NVARCHAR (255) NULL,
    [Date Introduced]                 DATETIME       NULL,
    [User Type]                       FLOAT (53)     NULL,
    [Easting]                         FLOAT (53)     NULL,
    [Northing]                        FLOAT (53)     NULL,
    [Positional Quality]              FLOAT (53)     NULL,
    [County Code]                     NVARCHAR (255) NULL,
    [County Name]                     NVARCHAR (255) NULL,
    [Local Authority Code]            NVARCHAR (255) NULL,
    [Local Authority Name]            NVARCHAR (255) NULL,
    [Ward Code]                       NVARCHAR (255) NULL,
    [Ward Name]                       NVARCHAR (255) NULL,
    [Country Code]                    NVARCHAR (255) NULL,
    [Country Name]                    NVARCHAR (255) NULL,
    [Region Code]                     NVARCHAR (255) NULL,
    [Region Name]                     NVARCHAR (255) NULL,
    [Parliamentary Constituency Code] NVARCHAR (255) NULL,
    [Parliamentary Constituency Name] NVARCHAR (255) NULL,
    [European Electoral Region Code]  NVARCHAR (255) NULL,
    [European Electoral Region Name]  NVARCHAR (255) NULL,
    [Primary Care Trust Code]         NVARCHAR (255) NULL,
    [Primary Care Trust Name]         NVARCHAR (255) NULL,
    [Lower Super Output Area Code]    NVARCHAR (255) NULL,
    [Lower Super Output Area Name]    NVARCHAR (255) NULL,
    [Middle Super Output Area Code]   NVARCHAR (255) NULL,
    [Middle Super Output Area Name]   NVARCHAR (255) NULL,
    [Output Area Classification Code] NVARCHAR (255) NULL,
    [Output Area Classification Name] NVARCHAR (255) NULL,
    [Longitude]                       FLOAT (53)     NULL,
    [Latitude]                        FLOAT (53)     NULL,
    [Spatial Accuracy]                NVARCHAR (255) NULL,
    [Last Uploaded]                   DATETIME       NULL,
    [Location]                        NVARCHAR (255) NULL,
    [Socrata ID]                      FLOAT (53)     NULL
);

