CREATE VIEW [DWH].PseudoSTconversion AS
SELECT 
TRY_CONVERT(NVARCHAR,[Postcode 1]) AS [Postcode 1],
TRY_CONVERT(NVARCHAR,[Postcode 2]) AS [Postcode 2],
TRY_CONVERT(NVARCHAR,[Postcode 3]) AS [Postcode 3],
TRY_CONVERT(DATE, [Date Introduced]) AS [Date Introduced],
TRY_CONVERT(FLOAT, [User Type]) AS [User Type],
TRY_CONVERT(FLOAT,[Easting]) AS [Easting],
TRY_CONVERT(FLOAT,[Northing]) AS [Northing],
TRY_CONVERT(FLOAT,[Positional Quality]) AS [Positional Quality],
TRY_CONVERT(NVARCHAR,[County Code]) AS [County Code],
TRY_CONVERT(NVARCHAR,[County Name]) AS [County Name],
TRY_CONVERT(NVARCHAR,[Local Authority Code]) AS [Local Authority Code],
TRY_CONVERT(NVARCHAR,[Local Authority Name]) AS [Local Authority Name],
TRY_CONVERT(NVARCHAR,[Ward Code]) AS [Ward Code],
TRY_CONVERT(NVARCHAR,[Ward Name]) AS [Ward Name],
TRY_CONVERT(NVARCHAR,[Country Code]) AS [Country Code],
TRY_CONVERT(NVARCHAR,[Country Name]) AS [Country Name],
TRY_CONVERT(NVARCHAR,[Region Code]) AS [Region Code],
TRY_CONVERT(NVARCHAR,[Region Name]) AS [Region Name],
TRY_CONVERT(NVARCHAR,[Parliamentary Constituency Code]) AS [Parliamentary Constituency Code],
TRY_CONVERT(NVARCHAR,[Parliamentary Constituency Name]) AS [Parliamentary Constituency Name],
TRY_CONVERT(NVARCHAR,[European Electoral Region Code]) AS [European Electoral Region Code],
TRY_CONVERT(NVARCHAR,[European Electoral Region Name]) AS [European Electoral Region Name],
TRY_CONVERT(NVARCHAR,[Primary Care Trust Code]) AS [Primary Care Trust Code],
TRY_CONVERT(NVARCHAR,[Primary Care Trust Name]) AS [Primary Care Trust Name],
TRY_CONVERT(NVARCHAR,[Lower Super Output Area Code]) AS [Lower Super Output Area Code],
TRY_CONVERT(NVARCHAR,[Lower Super Output Area Name]) AS [Lower Super Output Area Name],
TRY_CONVERT(NVARCHAR,[Middle Super Output Area Code]) AS [Middle Super Output Area Code],
TRY_CONVERT(NVARCHAR,[Middle Super Output Area Name]) AS [Middle Super Output Area Name],
TRY_CONVERT(NVARCHAR,[Output Area Classification Code]) AS [Output Area Classification Code],
TRY_CONVERT(NVARCHAR,[Output Area Classification Name]) AS [Output Area Classification Name],
TRY_CONVERT(FLOAT,[Longitude]) AS [Longitude],
TRY_CONVERT(FLOAT,[Latitude]) AS [Latitude],
TRY_CONVERT(NVARCHAR,[Spatial Accuracy]) AS [Spatial Accuracy],
TRY_CONVERT(DATE,[Last Uploaded]) AS [Last Uploaded],
TRY_CONVERT(NVARCHAR,[Location]) AS [Location],
TRY_CONVERT(FLOAT,[Socrata ID]) AS [Socrata ID]
FROM [SGT].[PseudoST]